
DROP TABLE IF EXISTS ACTIVITE;
CREATE TABLE ACTIVITE (
  ID_ACTIVITE int(11) NOT NULL AUTO_INCREMENT,
  DATE_ACTIVITE date DEFAULT NULL,
  DUREE_ACTIVITE varchar(255) DEFAULT NULL,
  ETAT varchar(255) DEFAULT NULL,
  INTITULE varchar(255) DEFAULT NULL,
  LIEU varchar(255) DEFAULT NULL,
  ID_ANIMATEUR int(11) DEFAULT NULL,
  ID_COMPOSANTE int(11) DEFAULT NULL,
  PRIMARY KEY (ID_ACTIVITE),
  CONSTRAINT FKCBF1E2FB1EF7EC2B FOREIGN KEY (ID_COMPOSANTE) REFERENCES COMPOSANTE (ID_COMPOSANTE),
  CONSTRAINT FKCBF1E2FB896D0094 FOREIGN KEY (ID_ANIMATEUR) REFERENCES COLLABORATEUR (ID_COLLABORATEUR),
  CONSTRAINT FKCBF1E2FBA30C0C66 FOREIGN KEY (ID_COMPOSANTE) REFERENCES PROJET (ID_PROJET)
);

--
-- Table structure for table BENIFICIAIRE
--

DROP TABLE IF EXISTS BENIFICIAIRE;
CREATE TABLE BENIFICIAIRE (
  ID_BENIFICIAIRE int(11) NOT NULL AUTO_INCREMENT,
  CIN varchar(255) DEFAULT NULL,
  ADRESSE varchar(255) DEFAULT NULL,
  AGE int(11) DEFAULT NULL,
  NOM varchar(255) DEFAULT NULL,
  NUMERO_TELEPHONE varchar(255) DEFAULT NULL,
  PAYS varchar(255) DEFAULT NULL,
  PRENOM varchar(255) DEFAULT NULL,
  VILLE varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID_BENIFICIAIRE)
);

--
-- Table structure for table BENIFICIAIRE_ACTIVITE
--

DROP TABLE IF EXISTS BENIFICIAIRE_ACTIVITE;
CREATE TABLE BENIFICIAIRE_ACTIVITE (
  ID_ACTIVITE int(11) NOT NULL,
  ID_BENIFICIAIRE int(11) NOT NULL,
  CONSTRAINT FKCE983F188E0F723F FOREIGN KEY (ID_ACTIVITE) REFERENCES ACTIVITE (ID_ACTIVITE),
  CONSTRAINT FKCE983F18F2A4BECD FOREIGN KEY (ID_BENIFICIAIRE) REFERENCES BENIFICIAIRE (ID_BENIFICIAIRE)
);

--
-- Table structure for table BILAN
--

DROP TABLE IF EXISTS BILAN;
CREATE TABLE BILAN (
  ID_BILAN int(11) NOT NULL AUTO_INCREMENT,
  fichierBilan longblob,
  INTITULE varchar(255) DEFAULT NULL,
  TYPE varchar(255) DEFAULT NULL,
  ID_PROJET int(11) DEFAULT NULL,
  FICHIER_BILAN longblob,
  PRIMARY KEY (ID_BILAN),
  CONSTRAINT FK3C463D27282A421 FOREIGN KEY (ID_PROJET) REFERENCES PROJET (ID_PROJET)
) ;

--
-- Table structure for table COLLABORATEUR
--

DROP TABLE IF EXISTS COLLABORATEUR;
CREATE TABLE COLLABORATEUR (
  TYPE_COLLABORATEUR varchar(31) NOT NULL,
  ID_COLLABORATEUR int(11) NOT NULL AUTO_INCREMENT,
  CIN varchar(255) DEFAULT NULL,
  ADRESSE varchar(255) DEFAULT NULL,
  DATE_NAISSANCE date DEFAULT NULL,
  EMAIL varchar(255) DEFAULT NULL,
  LIEU_NAISSANCE varchar(255) DEFAULT NULL,
  NOM varchar(255) DEFAULT NULL,
  NUMERO_TELEPHONE varchar(255) DEFAULT NULL,
  PRENOM varchar(255) DEFAULT NULL,
  PASSWORD varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID_COLLABORATEUR)
);

--
-- Table structure for table COLLABORATEUR_ACTIVITE
--

DROP TABLE IF EXISTS COLLABORATEUR_ACTIVITE;
CREATE TABLE COLLABORATEUR_ACTIVITE (
  ID_ACTIVITE int(11) NOT NULL,
  ID_COLLABORATEUR int(11) NOT NULL,
  CONSTRAINT FK33F1FB5B8E0F723F FOREIGN KEY (ID_ACTIVITE) REFERENCES ACTIVITE (ID_ACTIVITE),
  CONSTRAINT FK33F1FB5BDA599155 FOREIGN KEY (ID_COLLABORATEUR) REFERENCES COLLABORATEUR (ID_COLLABORATEUR)
);

--
-- Table structure for table COMPOSANTE
--

DROP TABLE IF EXISTS COMPOSANTE;
CREATE TABLE COMPOSANTE (
  ID_COMPOSANTE int(11) NOT NULL AUTO_INCREMENT,
  INTITULE varchar(255) DEFAULT NULL,
  ID_PROJET int(11) DEFAULT NULL,
  ID_THEMATIQUE int(11) DEFAULT NULL,
  PRIMARY KEY (ID_COMPOSANTE),
  CONSTRAINT FK28313117282A421 FOREIGN KEY (ID_PROJET) REFERENCES PROJET (ID_PROJET),
  CONSTRAINT FK283131189DE8917 FOREIGN KEY (ID_THEMATIQUE) REFERENCES THEMATIQUE (ID_THEMATIQUE)
);

--
-- Table structure for table PARTENAIRE
--

DROP TABLE IF EXISTS PARTENAIRE;
CREATE TABLE PARTENAIRE (
  ID_PARTENAIRE int(11) NOT NULL AUTO_INCREMENT,
  ADRESSE varchar(255) DEFAULT NULL,
  EMAIL varchar(255) DEFAULT NULL,
  NOM varchar(255) DEFAULT NULL,
  NUMERO_TELEPHONE varchar(255) DEFAULT NULL,
  TYPE varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID_PARTENAIRE)
);

--
-- Table structure for table PARTENAIRE_PROJET
--

DROP TABLE IF EXISTS PARTENAIRE_PROJET;
CREATE TABLE PARTENAIRE_PROJET (
  ID_PARTENAIRE int(11) NOT NULL,
  ID_PROJET int(11) NOT NULL,
  CONSTRAINT FK24D993D44A40E277 FOREIGN KEY (ID_PARTENAIRE) REFERENCES PARTENAIRE (ID_PARTENAIRE),
  CONSTRAINT FK24D993D47282A421 FOREIGN KEY (ID_PROJET) REFERENCES PROJET (ID_PROJET)
) ;

--
-- Table structure for table PORTEUR_PROJET
--

DROP TABLE IF EXISTS PORTEUR_PROJET;
CREATE TABLE PORTEUR_PROJET (
  ID_PORTEUR int(11) NOT NULL AUTO_INCREMENT,
  EMAIL varchar(255) DEFAULT NULL,
  NOM varchar(255) DEFAULT NULL,
  NUMERO_TELEPHONE varchar(255) DEFAULT NULL,
  PRENOM varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID_PORTEUR)
);

--
-- Table structure for table PROJET
--

DROP TABLE IF EXISTS PROJET;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE PROJET (
  ID_PROJET int(11) NOT NULL AUTO_INCREMENT,
  CATEGORIE varchar(255) DEFAULT NULL,
  DATE_DEBUT date DEFAULT NULL,
  DATE_FIN date DEFAULT NULL,
  DESCRIPTION varchar(255) DEFAULT NULL,
  INTITULE varchar(255) DEFAULT NULL,
  ID_ADMINISTRATEUR int(11) DEFAULT NULL,
  ID_PROPOSITION int(11) DEFAULT NULL,
  ID_RESPONSABLE int(11) DEFAULT NULL,
  PRIMARY KEY (ID_PROJET),
  CONSTRAINT FK8D2C40CC1296B13 FOREIGN KEY (ID_RESPONSABLE) REFERENCES COLLABORATEUR (ID_COLLABORATEUR),
  CONSTRAINT FK8D2C40CC31F655B9 FOREIGN KEY (ID_ADMINISTRATEUR) REFERENCES COLLABORATEUR (ID_COLLABORATEUR),
  CONSTRAINT FK8D2C40CCEAF0C0C3 FOREIGN KEY (ID_PROPOSITION) REFERENCES PROPOSITION (ID_PROPOSITION)
);

--
-- Table structure for table PROPOSITION
--

DROP TABLE IF EXISTS PROPOSITION;
CREATE TABLE PROPOSITION (
  ID_PROPOSITION int(11) NOT NULL AUTO_INCREMENT,
  ANNEXE longblob,
  BUDGET_PREVISIONNEL varchar(255) DEFAULT NULL,
  DATE_PREVISION date DEFAULT NULL,
  DUREE_ACTION varchar(255) DEFAULT NULL,
  OBJECTIF varchar(255) DEFAULT NULL,
  POPULATION_CIBLE varchar(255) DEFAULT NULL,
  THEMATIQUE varchar(255) DEFAULT NULL,
  TYPE_ACTION varchar(255) DEFAULT NULL,
  TYPE_SOUTIEN varchar(255) DEFAULT NULL,
  ZONE_GEOGRAPHIQUE varchar(255) DEFAULT NULL,
  ID_PORTEUR_PROJET int(11) DEFAULT NULL,
  PRIMARY KEY (ID_PROPOSITION),
  CONSTRAINT FKE354E2B670382C16 FOREIGN KEY (ID_PORTEUR_PROJET) REFERENCES PORTEUR_PROJET (ID_PORTEUR)
);

--
-- Table structure for table PUBLICATION
--

DROP TABLE IF EXISTS PUBLICATION;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE PUBLICATION (
  ID_PUBLICATION int(11) NOT NULL AUTO_INCREMENT,
  DESCRIPTION varchar(255) DEFAULT NULL,
  PHOTO longblob,
  TITRE varchar(255) DEFAULT NULL,
  ID_PROJET int(11) DEFAULT NULL,
  PRIMARY KEY (ID_PUBLICATION),
  CONSTRAINT FK400F360C7282A421 FOREIGN KEY (ID_PROJET) REFERENCES PROJET (ID_PROJET)
);

--
-- Table structure for table RAPPORT
--

DROP TABLE IF EXISTS RAPPORT;
CREATE TABLE RAPPORT (
  ID_RAPPORT int(11) NOT NULL AUTO_INCREMENT,
  fichierRapport longblob,
  INTITULE varchar(255) DEFAULT NULL,
  TYPE varchar(255) DEFAULT NULL,
  ID_PROJET int(11) DEFAULT NULL,
  FICHIER_RAPPORT longblob,
  PRIMARY KEY (ID_RAPPORT),
  CONSTRAINT FK6536E4027282A421 FOREIGN KEY (ID_PROJET) REFERENCES PROJET (ID_PROJET)
);

--
-- Table structure for table RENDEZ_VOUS
--

DROP TABLE IF EXISTS RENDEZ_VOUS;
CREATE TABLE RENDEZ_VOUS (
  ID_RENDEZVOUS int(11) NOT NULL AUTO_INCREMENT,
  DATE datetime DEFAULT NULL,
  SUJET varchar(255) DEFAULT NULL,
  ID_ADMINISTRATEUR int(11) DEFAULT NULL,
  ID_PORTEUR_PROJET int(11) DEFAULT NULL,
  PRIMARY KEY (ID_RENDEZVOUS),
  CONSTRAINT FK2EBBA11831F655B9 FOREIGN KEY (ID_ADMINISTRATEUR) REFERENCES COLLABORATEUR (ID_COLLABORATEUR),
  CONSTRAINT FK2EBBA11870382C16 FOREIGN KEY (ID_PORTEUR_PROJET) REFERENCES PORTEUR_PROJET (ID_PORTEUR)
);

--
-- Table structure for table THEMATIQUE
--

DROP TABLE IF EXISTS THEMATIQUE;
CREATE TABLE THEMATIQUE (
  ID_THEMATIQUE int(11) NOT NULL AUTO_INCREMENT,
  DESCRIPTION varchar(255) DEFAULT NULL,
  INTITULE varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID_THEMATIQUE)
) ;


-- Dump completed on 2017-04-17 15:34:46